REQUIRED_ENV_VARIABLES = (
    "GIFTS_TABLE",
    "GIFT_STORES_TABLE",
    "TEMPLATE_PATH",
    "OUTPUT_PATH",
    "SETTING_TABLE_PATH",
)

PATH_ENV_VARIABLES = "TEMPLATE_PATH", "OUTPUT_PATH", "SETTING_TABLE_PATH"
